AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: User API (local)

Resources:

  Products:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/lambda
      Runtime: go1.x
      Events:
        Health:
          Type: Api
          Properties:
            Path: /user
            Method: any