name: api-continuous-integration

on:
  workflow_dispatch:
  push:
    branches: '**'
    paths:
      - 'api/**'
  pull_request:
    branches: '**'
    paths:
      - 'api/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
        shell: bash
    environment: production
    env:
      working-directory: ./api

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Golang
        uses: actions/setup-go@v3
        with:
            go-version: '>=1.18.0'

      - name: Install Dependencies
        run: go mod download
        working-directory: ./api

      - name: Build Project
        run: go build ./...
        working-directory: ./api

      - name: Run Unit Tests
        run: go test ./...
        working-directory: ./api