name: client-continuous-integration

on:
  workflow_dispatch:
  push:
    branches: '**'
    paths:
      - 'client/**'
  pull_request:
    branches: '**'
    paths:
      - 'client/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      
    - name: Install Depdendencies
      run: npm ci
      working-directory: ./client

    - name: Build Project
      run: npm run build --if-present
      working-directory: ./client

    - name: Run Unit Tests
      run: npm test
      working-directory: ./client